// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Microsservices.Products.Infra.Context;

namespace Microsservices.Products.Infra.Migrations
{
    [DbContext(typeof(ProductDataContext))]
    [Migration("20231119223625_CreateTables")]
    partial class CreateTables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsservices.Products.Domain.Entities.Produto", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnName("produtoId")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnName("dataAtualizacao")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnName("dataCadastro")
                        .HasColumnType("datetime");

                    b.Property<string>("Descricao")
                        .HasColumnName("descricao")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Nome")
                        .HasColumnName("nome")
                        .HasColumnType("varchar(100)");

                    b.Property<int>("StatusProdutoId")
                        .HasColumnName("statusProdutoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StatusProdutoId");

                    b.ToTable("produto");
                });

            modelBuilder.Entity("Microsservices.Products.Domain.Entities.StatusProduto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("statusProdutoId")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao")
                        .HasColumnName("descricao")
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("statusProduto");
                });

            modelBuilder.Entity("Microsservices.Products.Domain.Entities.Produto", b =>
                {
                    b.HasOne("Microsservices.Products.Domain.Entities.StatusProduto", "StatusProduto")
                        .WithMany()
                        .HasForeignKey("StatusProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
